CREATE DATABASE IF NOT EXISTS ProgettoBea;
USE ProgettoBea;

CREATE TABLE IF NOT EXISTS PosizioniOccupate (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x INT NOT NULL,
    y INT NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);